export const colleges = [
    {
        rank: "#1",
        name: "IIT Madras - Indian Institute of Technology [IITM], Chennai",
        location: "Chennai, Tamil Nadu | AICTE Approved",
        course: "B.Tech Computer Science Engineering",
        cutoff: "JEE-Advanced 2023 Cutoff : 144",
        fees: "₹ 2,09,550",
        placement: "₹ 21,48,000",
        userReviews: "8.6 / 10",
        ranking: "#3/131 in India",
        featured: false,
    },
    {
        rank: "#2",
        name: "IIT Delhi - Indian Institute of Technology [IITD], New Delhi",
        location: "New Delhi, Delhi NCR",
        course: "B.Tech Mathematics and Computing",
        cutoff: "JEE-Advanced 2023 Cutoff : 115",
        fees: "₹ 2,54,650",
        placement: "₹ 25,82,000",
        userReviews: "8.7 / 10",
        ranking: "#1/35 in India",
        featured: false,
    },
    {
        rank: "#3",
        name: "Parul University, Vadodara",
        location: "Vadodara, Gujarat | AICTE, COA, PCI, INC, GNC Approved",
        course: "B.Tech",
        cutoff: "Cutoff Info Not Available",
        fees: "₹ 1,49,000",
        placement: "₹ 4,00,000",
        userReviews: "8.1 / 10",
        ranking: "#99/147 in India",
        featured: true,
    },
    {
        rank: "#4",
        name: "IIT Bombay - Indian Institute of Technology [IITB], Mumbai",
        location: "Mumbai, Maharashtra | AICTE, UGC Approved",
        course: "B.Tech Computer Science Engineering",
        cutoff: "JEE-Advanced 2023 Cutoff : 66",
        fees: "₹ 2,29,300",
        placement: "₹ 21,82,000",
        userReviews: "8.8 / 10",
        ranking: "#2/35 in India",
        featured: false,
    },
    {
        rank: "#5",
        name: "IIT Kanpur - Inidan Institude of Technology [IITK],Uttar Pradesh",
        location: "Kanpur,Uttar Pradesh | AICTE, UGC Approved",
        course: "B.Tech",
        cutoff: "JEE-Advanced 2023 Cutoff : 115",
        fees: "₹ 2,09,550",
        placement: "₹ 25,82,000",
        userReviews: "8.7 / 10",
        ranking: "#4/35 in India",
        featured: true,
    },
    {
        rank: "#6",
        name: "IIT Roorkee - Indian Institute of Technology [IITR],Uttarakhand",
        location: "Roorkee,Uttarakhand | AICTE, UGC Approved",
        course: "B.Tech",
        cutoff: "JEE-Advanced 2023 Cutoff : 115",
        fees: "₹ 2,29,300",
        placement: "₹21,82,000",
        userReviews: "8.7 / 10",
        ranking: "#6/35 in India",
        featured: false,
    },
    {
        rank: "#7",
        name: "IIT Guwahati - Indian Institute of Technology [IITG],Assam",
        location: "Guwahati,Assam | AICTE, UGC Approved",
        course: "B.Tech Computer Science Engineeringh",
        cutoff: "JEE-Advanced 2023 Cutoff : 115",
        fees: "₹ 2,54,650",
        placement: "₹21,82,000",
        userReviews: "8.7 / 10",
        ranking: "#7/35 in India",
        featured: false,
    },
    {
        rank: "#8",
        name: "IIT Hyderabad - Indian Institute of Technology [IITH],Telangana",
        location: "Hyderabad,Telangana | AICTE, UGC Approved",
        course: "B.Tech Computer Science Engineeringh",
        cutoff: "JEE-Advanced 2023 Cutoff : 115",
        fees: "₹ 2,34,000",
        placement: "₹26,82,000",
        userReviews: "8.7 / 10",
        ranking: "#8/35 in India",
        featured: true,
    },
    {
        rank: "#9",
        name: "NIT Trichy - National Institute of Technology [NITT],Tamil Nadu",
        location: "Tirchy,Tamil Nadu | AICTE, UGC Approved",
        course: "B.Tech Computer Science Engineeringh",
        cutoff: "JEE-Advanced 2023 Cutoff : 125",
        fees: "₹ 2,94,000",
        placement: "₹7,82,000",
        userReviews: "8.7 / 10",
        ranking: "#9/35 in India",
        featured: false,
    },
    {
        
        rank: "#10",
        name: "Indian Institute of Technology, BHU, Varanasi [IIT BHU],Uttar Pradesh",
        location: "Varanasi,Uttar Pradesh | AICTE, UGC Approved",
        course: "B.Tech Computer Science Engineeringh",
        cutoff: "JEE-Advanced 2023 Cutoff : 105",
        fees: "₹ 2,10,000 ",
        placement: "₹4,82,000",
        userReviews: "8.7 / 10",
        ranking: "#10/35 in India",
        featured: false,
    }
    // Add more data here...
];
